<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\User;
use App\Models\Batch;
use App\Models\Strain;
use App\Models\Phase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Filament\Actions\Action;
use Livewire\Livewire;
use App\Filament\Resources\Batches\Pages\ListBatches;

class HistoricalImportTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        \App\Observers\BatchObserver::clearProcessed();
    }

    /** @test */
    public function it_imports_historical_batches_from_csv()
    {
        // Arrange
        $user = User::factory()->create();
        $this->actingAs($user);

        $strain = Strain::factory()->create(['name' => 'Orellana Florida', 'slug' => 'orellana-florida']);
        $phase = Phase::firstOrCreate(['slug' => 'incubation'], ['name' => 'Incubation', 'order' => 1]);

        // Create mock CSV file
        // Header (skipped) + 3 Rows
        // Row 1: Orellana Florida (seeded)
        // Row 2: Orellana Florida (discarded)
        // Row 3: Orellana Florida (completed + harvest)
        "Orellana Florida,01-01-2024,grain,5,2.5,discarded,contaminated,,,\"Observación de prueba\"\n" .
            "Orellana Florida,01-12-2023,grain,20,3.0,completed,,15,5,15-01-2024,"; // "15,5" yield might split if unquoted?
        // CSV parsing split by comma. "15,5" is two columns if not quoted.
        // If user file is standard CSV, float fields with commas MUST be quoted "15,5".
        // If they are not quoted, it shifts columns.
        // OR if they use using semi-colon delimiter? My code uses default `fgetcsv` which is comma.
        // Assuming standard CSV where "15,5" is the value.
        // If fgetcsv sees 15,5 without quotes, it sees 15 and 5.
        // Let's assume standard behavior: quoted "15,5" OR they mean point "15.5".
        // But if they provided a file generated by Excel in Spanish locale, it might use semicolon delimiter?
        // `fgetcsv` defaults to comma. If file is semicolon, `fgetcsv` puts whole line in row[0] or weird split.
        // If comma delimiter, but "15,5" is value -> Must be quoted.
        // Let's try simulating "15,5" as yield.
        // "...,completed,,\"15,5\",..."

        $csvContent = "strain,date,type,quantity,bag_weight,status,reason,harvest_yield,harvest_date,observations,origin_code,container_type\n" .
            "Orellana Florida,10-06-2025,grain,10,2.5,seeded,,,,,CL-001,bag\n" .
            "Orellana Florida,01-01-2024,grain,5,2.5,discarded,contaminated,,,\"Observación de prueba\",,jar\n" .
            "Orellana Florida,01-12-2023,grain,20,3.0,completed,,\"15,5\",15-01-2024,,PP-05,bag";

        Storage::disk('local')->put('imports/test.csv', $csvContent);

        // Act: Call the action
        Livewire::test(ListBatches::class)
            // .set('attachment', ['imports/test.csv']) // Direct set might not work for Action form
            ->callAction('importHistory', [
                'attachment' => ['imports/test.csv'], // FileUpload expects array usually
            ])
            ->assertNotified(); // Expect success notification

        // Assert

        // 1. Check Batch 1
        $batch1 = Batch::whereDate('inoculation_date', '2025-06-10')->first();
        $this->assertNotNull($batch1);
        $this->assertEquals('seeded', $batch1->status);
        $this->assertEquals(10, $batch1->quantity);
        $this->assertEquals(true, $batch1->is_historical);
        // Code check: ORE-100625-1 (assuming empty DB)
        $this->assertEquals('ORE-100625-1', $batch1->code);

        // Check Origin Code
        $this->assertEquals('CL-001', $batch1->origin_code);
        $this->assertEquals('bag', $batch1->container_type);

        // 2. Check Batch 2
        $batch2 = Batch::whereDate('inoculation_date', '2024-01-01')->first();
        $this->assertNotNull($batch2);
        $this->assertEquals('grain', $batch2->type);
        $this->assertEquals('jar', $batch2->container_type);
        $this->assertEquals('discarded', $batch2->status);
        $this->assertNull($batch2->origin_code); // Should be null as CSV had explicit empty
        $this->assertEquals('Observación de prueba', $batch2->observations);
        // Check Loss
        $loss = \App\Models\BatchLoss::where('batch_id', $batch2->id)->first();
        $this->assertNotNull($loss);
        // Reason is set by Observer to default 'Mala calidad' or similar, strict mapping not implemented in Action
        // $this->assertEquals('contaminated', $loss->reason); 
        $this->assertEquals('contaminated', $loss->reason);

        // Detail should contain the CSV reason
        $this->assertStringContainsString('contaminated (Importado)', $loss->details);

        // 3. Check Batch 3 (Completed with Harvest)
        $batch3 = Batch::whereDate('inoculation_date', '2023-12-01')->first();
        $this->assertNotNull($batch3);
        $this->assertEquals('completed', $batch3->status);
        $this->assertEquals('PP-05', $batch3->origin_code);
        $this->assertEquals('bag', $batch3->container_type);
        // Check Harvest
        $harvest = \App\Models\Harvest::where('batch_id', $batch3->id)->first();
        $this->assertNotNull($harvest);
        $this->assertEquals(15.5, $harvest->weight);
        $this->assertEquals('2024-01-15', $harvest->harvest_date->toDateString());
    }
}
